/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Passball | KLYW</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="flex flex-col items-center justify-center gap-6">
        <img
          className="mb-20 w-[300px] object-contain"
          src="/assets/LOGO_MVP.png"
        />

        <button
          onClick={() => router.push("/male")}
          className="w-[200px] border border-b-4 border-white bg-black py-4 text-white hover:border-b"
        >
          男生
        </button>
        <button
          onClick={() => router.push("/female")}
          className="w-[200px] border border-b-4 border-white bg-black py-4 text-white hover:border-b"
        >
          女生
        </button>
      </div>
    </>
  );
}
